spring.application.name=telemetry-api


spring.datasource.url=jdbc:postgresql://localhost:5432/sensor_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASS}
mqtt.broker.url=tcp://${MQTT_BROKER_IP:localhost}:1883
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

server.error.include-message=always
